site_name: brandonnodnarb

repo_url: https://brandonnodnarb.github.io
repo_name: brandonnodnarb.github.io
site_description: brandon's io
site_author: brandonnodnarb

pages:
- home: index.md
- about: about.md
- projects: projects.md
- cv: cv.md

theme: cyborg
