site_name: brandonnodnarb

repo_url: brandonnodnarb.github.io
repo_name:
site_description: brandon's io
site_author: brandonnodnarb

pages:
- home: index.md
- about: about.md
- projects: projects.md
- cv: cv.md

theme: cyborg
