site_name: popokotea

site_url: http://www.popokotea.org
#repo_url: https://github.com/brandonnodnarb/brandonnodnarb.github.io
#repo_name: github
site_author: brandon

#site_description: brandon's spinning dodecahedron

pages:
- index.md
#- projects: projects.md
#- cv: cv.md

#theme: cinder
#theme: bootstrap
theme: cyborg
#theme_dir: 'mkdocs_docskimmer'
